
name: Build

on: [push, pull_request]

jobs:
  linux-core:
    runs-on: ubuntu-16.04
    name: linux-${{ matrix.image }}-${{ matrix.compiler }}-llvm:${{ matrix.llvm }}-${{ matrix.build }}
    container:
      image: aswf/ci-vfxall:${{ matrix.image }}
    env:
      LLVM_VERSION: ${{ matrix.llvm }}
      LLVM_ROOT_DIR: /github/home/llvm-${{ matrix.llvm }}
      CXX: ${{ matrix.compiler }}
    strategy:
      matrix:
        image: ['2019']
        compiler: ['g++']
        build: ['Release']
        llvm: ['8.0.0']
    steps:
      - uses: actions/checkout@v1
      - name: install_llvm
        run: ./ci/install_llvm.sh
      - name: build
        run: |
          ./ci/build.sh \
            -DCMAKE_BUILD_TYPE=${{ matrix.build }} \
            -DLLVM_DIR=/github/home/llvm-${{ matrix.llvm }}/lib/cmake/llvm \
            -DOPENVDB_CXX_STRICT=ON
      - name: test
        run: cd build && ctest -V
