
name: Build

on: [push, pull_request]

jobs:
  linux-core:
    runs-on: ubuntu-16.04
    name: linux:${{ matrix.image }}-compiler:${{ matrix.compiler }}-llvm:${{ matrix.llvm }}-${{ matrix.build }}
    container:
      image: aswf/ci-vfxall:${{ matrix.image }}
    env:
      CXX: ${{ matrix.compiler }}
      LLVM_DIR: /github/home/llvm-${{ matrix.llvm }}-${{ matrix.compiler }}
    strategy:
      matrix:
        image: ['2019']
        compiler: ['g++', 'clang++']
        build: ['Release']
        llvm: ['7.0.0']
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: llvm_cache
        id: llvm_cache
        uses: actions/cache@v1
        with:
          key: ${{ env.LLVM_DIR }}
          path: ${{ env.LLVM_DIR }}
      - name: install_llvm
        if: steps.llvm_cache.outputs.cache-hit != 'true'
        run: ./ci/install_llvm.sh ${{ matrix.llvm }} ${{ env.LLVM_DIR }}
      - name: install_libedit
        run: yum -y install libedit-devel
      - name: build
        run: |
          ./ci/build.sh \
            -DCMAKE_BUILD_TYPE=${{ matrix.build }} \
            -DLLVM_DIR=${{ env.LLVM_DIR }} \
            -DOPENVDB_CXX_STRICT=ON
      - name: test
        run: cd build && ctest -V
