
name: Build

on: [push, pull_request]

jobs:
  linux-core:
    runs-on: ubuntu-18.04
    name: linux:${{ matrix.image }}-compiler:${{ matrix.compiler }}-llvm:${{ matrix.llvm }}-${{ matrix.build }}
    container:
      image: aswf/ci-vfxall:${{ matrix.image }}
    env:
      CXX: ${{ matrix.compiler }}
    strategy:
      matrix:
        image: ['2019']
        compiler: ['g++', 'clang++']
        build: ['Release']
        llvm: ['7.0.0']
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: install_llvm
        run: ./ci/install_llvm.sh ${{ matrix.llvm }} /github/home/llvm-${{ matrix.llvm }}
      - name: install_libedit
        run: yum -y install libedit-devel
      - name: build
        run: |
          ./ci/build.sh \
            -DCMAKE_BUILD_TYPE=${{ matrix.build }} \
            -DLLVM_DIR=/github/home/llvm-${{ matrix.llvm }}/lib/cmake/llvm \
            -DOPENVDB_CXX_STRICT=ON
      - name: test
        run: cd build && ctest -V
